Dorm.where(name: "Babcock Hall").first_or_create!;
Dorm.where(name: "Bostwick Hall").first_or_create!;
Dorm.where(name: "Collins Hall").first_or_create!;
Dorm.where(name: "Davis Hall").first_or_create!;
Dorm.where(name: "Dogwood Hall").first_or_create!;
Dorm.where(name: "Efird Hall").first_or_create!;
Dorm.where(name: "Huffman Hall").first_or_create!;
Dorm.where(name: "Johnson Hall").first_or_create!;
Dorm.where(name: "Kitchin Hall").first_or_create!;
Dorm.where(name: "Luter Hall").first_or_create!;
Dorm.where(name: "Magnolia Hall").first_or_create!;
Dorm.where(name: "Martin Hall").first_or_create!;
Dorm.where(name: "Palmer Hall").first_or_create!;
Dorm.where(name: "Piccolo Hall").first_or_create!;
Dorm.where(name: "Polo Hall").first_or_create!;
Dorm.where(name: "Poteat Hall").first_or_create!;
Dorm.where(name: "South Hall Hall").first_or_create!;
Dorm.where(name: "Taylor Hall").first_or_create!;
Dorm.where(name: "Student Apts").first_or_create!;
Dorm.where(name: "North Campus Apts").first_or_create!;
Dorm.where(name: "Off Campus").first_or_create!;
Dorm.where(name: "Other").first_or_create!;